<a href="https://colab.research.google.com/github/KxxHyoRim/Data-Mining/blob/main/DM_final_combine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Week7 Naive Bayes**
- 나이브 베이즈 코드 출제 예정

<br/>

**Naive Bayes (Iris)**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=0)
gnb = GaussianNB()

y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabled points out of a total %d points : %d " %
      (X_test.shape[0],            # test data size 
       (y_test != y_pred).sum()))  # wrong count

Number of mislabled points out of a total 75 points : 4 


In [ ]:
# 나이브 베이즈 student 데이터로 연습해봄
from google.colab import drive

drive.mount('/content/drive')
file_name = '/content/drive/My Drive/Data Mining/student_health_3.csv'

data = pd.read_csv(file_name, encoding='cp949')
df = pd.DataFrame(data, columns=['키', '몸무게', '학년', '수축기', '이완기'])

df.head(3)
df['학년'].unique() # 1,4학년

x = df[['키', '몸무게', '수축기', '이완기']].values
y = df['학년'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=0)
gnb = GaussianNB()

a = gnb.fit(X_train, y_train)
y_pred = a.predict(X_test)

prob = a.predict_proba(X_test)

print("Number of mislabled points out of a total %d points : %d " %
      (X_test.shape[0],            # test data size 
       (y_test != y_pred).sum()))  # wrong count

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Number of mislabled points out of a total 563 points : 31 


## **Week9 Classification and Regression Trees**
- Decision Tree
- Random Forest

**Decision Tree**

In [ ]:
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
# print(iris)   #dictionary / json 형식인듯
X, y = iris.data, iris.target
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)

# clf.predict(X)

# tree.plot_tree(clf)

**Random Forest(권장)**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

X, y = make_classification(n_samples = 1000, n_features = 4,
                           n_informative = 2, n_redundant = 0, 
                           random_state = 0, shuffle = False)

clf = RandomForestClassifier(max_depth=2, random_state=0)         # max_depth
clf.fit(X, y)

# RandomForestClassifier(..) 강의확인할것

clf.predict([[0,0,0,0]])

array([1])

**3. student health로 연습**
아래 코드는 decision tree 이긴 한데, <br/>
밑에 생성자만 바꾸면 random도 쓸 수 있음

In [ ]:
from sklearn.model_selection import train_test_split

data = pd.read_csv(file_name, encoding='cp949')
df = pd.DataFrame(data, columns=['키', '몸무게', '학년', '수축기', '이완기'])

df.head(3)
df['학년'].unique() # 1,4학년

X = df[['키', '몸무게', '수축기', '이완기']].values
y = df['학년'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=0)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
# print(y_pred)
# print(y_test)

clf.score(X_test,y_test)

0.9431616341030196

## **Week10 Logistic Regression**

**1. Logistic 코드 공부**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

X,y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0).fit(X, y)

clf.predict(X[:2, :])
clf.predict_proba(X[:2, :])
clf.score(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.9733333333333334

**2. Linear 와의 차이점**

- Logistic은 카테고리 분류에 유리
  - Binary : Sigmoid
  - Multi : Softmax

- Linear는 선긋기를 통한 예측값 구하기 (ex. 집 값)

#### **3. 과제 : student_health_3.csv에서 학년을 도출하는 Logistic Regression 구하기**

predict, predict_proba 구할 때 x dataframe이랑 동일한 순서의 데이터 넣어줘야됨

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

from google.colab import drive
drive.mount('/content/drive')
file_name = '/content/drive/My Drive/Data Mining/student_health_3.csv'

df = pd.read_csv(file_name, encoding='cp949')
df.head(3)
df['학년'].unique() # 1,4학년

x = df[['키', '몸무게', '수축기', '이완기']]
y = df['학년']

clf = LogisticRegression(random_state=0).fit(x, y)
score = clf.score(x,y)
predict =  clf.predict([[125.8, 27.3, 77, 58]])     # '키', '몸무게', '수축기', '이완기'
predict_proba = clf.predict_proba([[125.8, 27.3, 77, 58]])

print("Score : " , score)
print("Predict : ",predict)
print("Predict Probability : " , predict_proba)

Mounted at /content/drive
Score :  0.9591111111111111
Predict :  [1]
Predict Probability :  [[0.9643986 0.0356014]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


## **Week11 Neural Network**

**1. MLPClassifier (시험 출제 확률 높음)**

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=1)
clf = MLPClassifier(random_state = 1, max_iter = 300).fit(X_train, y_train)
clf.predict_proba(X_test[:5, :])
clf.score(X_test, y_test)

0.88

**2. MLPRegressor**

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

X, y = make_regression(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1)
regr = MLPRegressor(random_state = 1, max_iter = 500).fit(X_train, y_train)
regr.predict(X_test[:2])
round(regr.score(X_test, y_test), 3)

# 회귀분석이라서 정확률은 많이 떨어짐

# clf.predict_proba(X_test[:5, :])
# 'MLPRegressor' object has no attribute 'predict_proba'

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


0.106

#### **3. 과제 (Assignment8)**
#### **Neural Network와 기존 방법과 비교 (student_health)**


In [ ]:
# -*- coding: utf-8 -*-
import pandas as pd
import time
from google.colab import drive
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

"""
1. 해당 데이터는 모두 초등학생으로 구성됨
2. 1~6학년 까지의 데이터가 있음
3. 수축기와, 이완기 column의 경우 1,4학년의 데이터만 있음
"""

def callKNN(X, y):
  
  # 데이터 분리
  X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)
  # KNN Train
  start_time = time.time()
  kn = KNeighborsClassifier()
  kn.fit(X_train, y_train)
  end_time = time.time()
  print("훈련 속도 : ", end_time - start_time )
  # 점수 산정
  print("KNN Score", kn.score(X_test, y_test))
  # Predict KNN
  print( y_test[:5] , "# Real Data")
  print(kn.predict(X_test[:5, :]),  "# Predicted Data\n\n")

def callNN(X, y):
  
  X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)
    
  # MLP Classifier Train
  start_time = time.time()
  clf = MLPClassifier().fit(X_train, y_train)
  end_time = time.time()
  print("훈련 속도 : ", end_time - start_time )
  # MLP 점수 산정
  print("NN Score ", clf.score(X_test, y_test))
  # Predict MLP 
  print(y_test[:5] , "# Real Data")
  print(clf.predict(X_test[:5, :]), "# Predicted Data\n\n")



if __name__=="__main__" :
    
  drive.mount('/content/drive')
  csv = '/content/drive/My Drive/Data Mining/student_health_2.csv'

  data = pd.read_csv(csv,  encoding='cp949')
  df = pd.DataFrame(data, columns=['키', '몸무게', '학년', '수축기', '이완기'])

  # 2개의 feature로 6개 카테고리 분류
  X = df[['키', '몸무게']].values
  y = df['학년'].values

  callKNN(X, y)
  callNN(X,y)


  # 4개의 feature로 6개 카테고리 분류
  df = df.dropna()      # 수축기와 이완기 데이터가 없는 row 제거
  X = df[['키', '몸무게', '수축기', '이완기']].values
  y = df['학년'].values

  callKNN(X, y)
  callNN(X,y)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
훈련 속도 :  0.0017070770263671875
KNN Score 0.45352743561030234
[3 5 6 2 2] # Real Data
[2 6 5 3 1] # Predicted Data


훈련 속도 :  0.3522977828979492
NN Score  0.3169092945128779
[3 5 6 2 2] # Real Data
[3 3 6 3 3] # Predicted Data


훈련 속도 :  0.0014255046844482422
KNN Score 0.9645390070921985
[4 4 1 4 4] # Real Data
[4 4 1 4 4] # Predicted Data


훈련 속도 :  0.6190905570983887
NN Score  0.8156028368794326
[4 4 1 4 4] # Real Data
[1 4 1 4 1] # Predicted Data




#### **4. VerySimpleCnn**

In [ ]:
import tensorflow
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
import numpy as np

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000,28,28,1)
x_test = x_test.reshape(10000,28,28,1)

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = tensorflow.keras.utils.to_categorical(y_train, num_classes)
y_test = tensorflow.keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(28,28,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy, optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Epoch 1/12
469/469 [==============================] - 150s 318ms/step - loss: 0.7125 - accuracy: 0.8686 - val_loss: 0.0839 - val_accuracy: 0.9746
Epoch 2/12
469/469 [==============================] - 143s 305ms/step - loss: 0.1536 - accuracy: 0.9554 - val_loss: 0.0539 - val_accuracy: 0.9832
Epoch 3/12
469/469 [==============================] - 143s 304ms/step - loss: 0.1160 - accuracy: 0.9665 - val_loss: 0.0537 - val_accuracy: 0.9834
Epoch 4/12
469/469 [==============================] - 143s 305ms/step - loss: 0.0937 - accuracy: 0.9726 - val_loss: 0.0442 - val_accuracy: 0.9873
Epoch 5/12
469/469 [==============================] - 143s 306ms/step - loss: 0.0788 - accuracy: 0.9768 - val_loss: 0.0414 - val_accuracy: 0.9886
Epoch 6/12
469/469 [==============================] - 143s 304ms/step - loss: 0.0749 - accuracy: 0.9775 - val_loss: 0.0451 - val_accuracy: 0.9866
Epoch 7/12
469/469 [==============================]

## **Week12 Discriminant Analysis**

<br/>

**Linear Discriminant Analysis**

In [ ]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X = np.array([[-1,-1], [-2, -1], [-3, -2], [1, 1], [2,1], [3,2]])
y = np.array([1,1,1,2,2,2])
clf = LinearDiscriminantAnalysis()
clf.fit(X, y)
print(clf.predict([[-0.8, -1]]))

[1]


**Quadratic Discriminant Analysis**

In [ ]:
import numpy as np
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

X = np.array([[-1,-1], [-2, -1], [-3, -2], [1, 1], [2,1], [3,2]])
y = np.array([1,1,1,2,2,2])
clf = QuadraticDiscriminantAnalysis()
clf.fit(X, y)
print(clf.predict([[-0.8, -1]]))

[1]


#### **과제 (Assignment 9)**

Linear/Quadratic student_health에 저장하기

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from google.colab import drive


drive.mount('/content/drive')

#불러올 파일의 경로를 filename 변수에 저장
file_name = '/content/drive/My Drive/Data Mining/student_health_assignment9.csv'

data = pd.read_csv(file_name,  encoding='cp949')
# print(data.shape)
data.head(1)

''' 데이터 구성 확인 '''
grade = data['학년']
grade.value_counts()  # 1, 4학년만 있음

''' 데이터 로드 '''
std = pd.DataFrame(data, columns=['수축기', '이완기', '키', '몸무게', '학년'])
std = std.dropna()  # null 처리 
std.isnull().sum()  # null 확인 

X = std[['키', '몸무게', '수축기', '이완기']].values
y = std[['학년']].values

''' 데이터 분리 '''
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                    random_state=1)


''' Linear '''
clf = LinearDiscriminantAnalysis()
clf.fit(X ,y)
print(clf.predict (X_test[:5, :]))            #
print("score", clf.score(X_test, y_test))     #

''' Quadratic '''
clf = QuadraticDiscriminantAnalysis()
clf.fit(X ,y)
print(clf.predict (X_test[:5, :]))            #
print("score", clf.score(X_test, y_test))     #

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(282, 4)
[4 4 1 4 4]
score 0.9680851063829787
[4 4 1 4 4]
score 0.9574468085106383


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(X_test.shape)
X_test[:3, :]

(282, 4)


array([[133.4,  36.1, 102. ,  78. ],
       [150. ,  49.1, 125. ,  70. ],
       [117.8,  22.8,  90. ,  60. ]])

#### **과제 (Assignment 10)**
#### **K-mean Clustering student_health_3에 적용**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from google.colab import drive

drive.mount('/content/drive')
file_name = '/content/drive/My Drive/Data Mining/student_health_3.csv'

data = pd.read_csv(file_name,  encoding='cp949')
data.head(1)

grade = data['학년']
grade.value_counts()  # 1, 4학년만 있음

std = pd.DataFrame(data, columns=['수축기', '이완기', '키', '몸무게', '학년'])
std = std.dropna()                    # null 값 처리

std.loc[std['학년'] == 1, '학년'] = 1     # 1학년(저학년)을 Class1로 변경
std.loc[std['학년'] == 4, '학년'] = 2     # 4학년(고학년)을 Class2로 변경

X = std[['키', '몸무게', '수축기', '이완기']].values
y = std[['학년']].values

''' 데이터 분리 '''
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    stratify=y,     # 비율 유지 위함
                                                    random_state=1)

''' K-mean Clustring '''
kmeans = KMeans(n_clusters=2, random_state=0).fit(X_train)


''' Print result '''
# 데이터 분리시 train 데이터 실제값과 예측값
size = 10
print("[Train]")
print(y_train[:size, 0])
print(kmeans.labels_[:size])

# 데이터 분리시 test 데이터 실제값과 예측값
print("\n[Test]")
print(kmeans.predict (X_test[:size, :]))
print(y_test[:size, 0])


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[Train]
[2 2 2 2 1 1 1 2 1 1]
[0 0 0 0 1 1 1 1 0 1]

[Test]
[0 0 1 1 1 0 0 1 0 1]
[2 2 1 2 2 2 2 2 2 1]
