<a href="https://colab.research.google.com/github/KxxHyoRim/Data-Mining/blob/main/student_health_cpr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from google.colab import drive

#불러올 파일의 경로를 filename 변수에 저장
drive.mount('/content/drive')
file = '/content/drive/My Drive/Data Mining/student_health_2.csv'

# Load Data
data = pd.read_csv(file,  encoding='cp949')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


데이터 확인 결과 알게된 사실

1. 해당 데이터는 모두 초등학생으로 구성됨
2. 1~6학년 까지의 데이터가 있음
3. 수축기와, 이완기 column의 경우 1,4학년의 데이터만 있음

데이터 전처리에 대한 코드는 직접적으로 LMS에 첨부하지 않으나 아래 링크에서 확인 가능합니다.

https://colab.research.google.com/drive/1XNDlWXO3YZNt0e4UzrcOociU3vzPG9dF#scrollTo=CkMFpbQNMMN6

In [6]:
def callKNN(X, y):
  
  # 2. 데이터 분리
  X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)

  # 3. KNN Train
  start_time = time.time()
  kn = KNeighborsClassifier()
  kn.fit(X_train, y_train)
  end_time = time.time()
  print("훈련 속도 : ", end_time - start_time )

  # 4. 점수 산정
  print("KNN Score", kn.score(X_test, y_test))

  # 5. Predict KNN
  print( y_test[:5] , "# Real Data")
  print(kn.predict(X_test[:5, :]),  "# Predicted Data\n\n")

In [7]:
def callNN(X, y):
  
  # 2. 데이터 분리
  X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)
    
  #3. MLP Classifier 훈련
  start_time = time.time()
  clf = MLPClassifier().fit(X_train, y_train)
  end_time = time.time()
  print("훈련 속도 : ", end_time - start_time )

  #4. MLP 점수 산정 = 정확률 계산
  print("NN Score ", clf.score(X_test, y_test))


  #5. MLP 예측
  print(y_test[:5] , "# Real Data")
  print(clf.predict(X_test[:5, :]), "# Predicted Data\n\n")

In [8]:
if __name__=="__main__" :
  df = pd.DataFrame(data, columns=['키', '몸무게', '학년', '수축기', '이완기'])

  # 2개의 feature로 6개 카테고리 분류

  X = df[['키', '몸무게']].values
  y = df['학년'].values

  callKNN(X, y)
  callNN(X,y)


  # 4개의 feature로 6개 카테고리 분류
  df = df.dropna()      # 수축기와 이완기 데이터가 없는 row 제거

  X = df[['키', '몸무게', '수축기', '이완기']].values
  y = df['학년'].values

  callKNN(X, y)
  callNN(X,y)

훈련 속도 :  0.0014650821685791016
KNN Score 0.45352743561030234
[3 5 6 2 2] # Real Data
[2 6 5 3 1] # Predicted Data


훈련 속도 :  0.5016984939575195
NN Score  0.3023516237402016
[3 5 6 2 2] # Real Data
[2 2 6 2 2] # Predicted Data


훈련 속도 :  0.0011172294616699219
KNN Score 0.9645390070921985
[4 4 1 4 4] # Real Data
[4 4 1 4 4] # Predicted Data


훈련 속도 :  0.453338623046875
NN Score  0.8368794326241135
[4 4 1 4 4] # Real Data
[4 4 1 4 4] # Predicted Data


